---
author: "Manuel Alejandro Costan Macareño"
date: "22/10/2022"
documentclass: book
forprint: false  # true: imprime a dos caras, false: libro digital
fontsize: 12pt # 10pt,11pt
geometry: margin = 2.5cm 
bibliography: ["bib/library.bib", "bib/paquetes.bib"]
metodobib: true  # true: natbib (descomentar: citation_package: natbib) 
#                  false: pandoc (comentar: citation_package: natbib)
#natbib: plainnat, abbrvnat, unsrtnat
biblio-style: "plainnat"
#Método 2 (pandoc): descomente una línea de las 2 siguientes en caso de usarlo
#csl: methods-in-ecology-and-evolution.csl      # no numera mejor en las citas
csl: acm-sig-proceedings-long-author-list.csl  # numera peor en las citas
link-citations: yes
output: 
  pdf_document:
    keep_tex: no
    number_sections: yes
    citation_package: natbib  # comentado usa: pandoc-citeproc
    #toc: yes
    fig_caption: yes
    template: latex/templateMemoriaTFE.tex
    includes:
      #before_body: portadas/latex_paginatitulo_modTFE.tex
      #in_header: latex/latex_preambulo.tex
      #after_body: latex/latex_antes_enddoc.tex
---



```{r include=FALSE}
knitr::opts_chunk$set(fig.path = 'figurasR/',
                      echo = FALSE, warning = FALSE, message = FALSE,
                      fig.pos="H",fig.align="center",out.width="95%",
                      cache=FALSE)

```


<!-- \setcounter{chapter}{2} -->
<!-- \setcounter{chapter}{2} escribir 2 para capítulo 3  -->
<!-- \pagenumbering{arabic} -->

\ifdefined\ifprincipal
\else
\setlength{\parindent}{1em}
\pagestyle{fancy}
\setcounter{tocdepth}{4}
\tableofcontents
<!-- \nocite{*} -->
\fi

\ifdefined\ifdoblecara
\fancyhead{}{}
\fancyhead[LE,RO]{\scriptsize\rightmark}
\fancyfoot[LO,RE]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[LE,RO]{\footnotesize\thepage}
\else
\fancyhead{}{}
\fancyhead[RO]{\scriptsize\rightmark}
\fancyfoot[LO]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[RO]{\footnotesize\thepage}
\fi
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}


# Modelos de regresión

Existen diferentes métodos estadísticos que permiten evaluar la relación existente entre dos o más variables en forma de función matemática. Para llevar a cabo la modelización que puede llegar a tener la depreciación del valor de las cabezas tractoras en función de diferentes variables y evaluar cómo estas afectan tanto de forma independiente como conjunta a la depreciación de las maquinarias, se utilizaran diversos modelos de regresión.

El primer modelo de regresión a utilizar consiste en un modelo predictivo o de regresión por el método de mínimos cuadrados, específicamente modelos de regresión. Estos se basan en la relación de la variable exógena (precio de venta) con la variable o las variables endógenas (edad del maquinaria, kilómetros recorridos). Por tanto, no es un modelo de valoración, ya que no utilizamos para valorar un activo sino para obtener la tasa de depreciación. 

Como indica [@MDFD2008MD], un modelo de regresión lineal: es una técnica de modelado estadístico que consiste en generar un modelo de regresión para describir una variable dependiente, o respuesta continua (Y) como una función de una o varias variables independientes, o predictoras (X). Este modelo permite comprender y predecir el comportamiento de sistemas complejos o a analizar datos experimentales, financieros y biológicos. Esta se describe de acuerdo con la siguiente ecuación:

$$
Y= β_0+ ∑_{i=1}^nβ_n X_n 
$$
Como existe la posibilidad que el conjunto de datos no se llegue a explicar bien por una relación lineal, se llevaran a cabo unas variaciones partiendo de la anterior ecuación, para tratar de encontrar método de regresión exponencial y potencial que lleguen a explicar mejor el modelo.

 Un modelo de regresión exponencial es una técnica que busca encontrar la ecuación de la función exponencial $Y= β_0* β_1^X$ que se ajuste mejor a un conjunto de datos, y que, al sacarle logaritmo, se obtendría la siguiente ecuación:

$$
ln⁡(Y)= ln⁡(β_0)+ ∑_{i=1}^nβ_n X_n 
$$

Un modelo de regresión potencial es aquel en el que la función de ajuste es una función del tipo potencial del tipo $Y= β_0*X^{β_1}$, el cual, según [@MDFD2008MD], al linealizarlo, se obtendría la siguiente expresión:

$$
ln⁡(Y)= ln⁡(β_0)+ ∑_{i=1}^n β_n*ln⁡(X_n ) 
$$
En la siguiente tabla se puede observar un resumen de las diferentes ecuaciones empleadas para la modelización de la depreciación de las cabezas tractoras:

<!--poner tabla con las ecuaciones que esta en el word, falta ajustar las ecuaciones a modelos con multiples variables-->


# Bondad del ajuste del modelo

La bondad de ajuste de un modelo de regresión se refiere al grado en que éste es conveniente como modelo que representa a las variables implicadas en el mismo. Tal como hemos visto, al ajustar un modelo de regresión a la distribución conjunta de 2 variables obtendremos la mejor recta de regresión de entre todas las posibles que se pueden ajustar a esa distribución, ahora bien, ello no significa que sea buena como modelo que represente a ambas variables. Las medidas más utilizadas para medir la calidad del ajuste son: error estándar de los residuos (RSE), el test F y el utilizado en este trabajo, el coeficiente de determinación R2.

Coeficiente de determinación R2: Describe la proporción de variabilidad observada en la variable dependiente Y explicada por el modelo y relativa a la variabilidad total, es decir, valora si la regresión que estamos aplicando es representativa y puede predecir el valor de manera adecuada. Su coeficiente está acotado entre 0 y 1, de modo que cuanto más próximo sea el valor a 1mejor será la bondad de ajuste del modelo de regresión a la distribución conjunta de las variables. Al ser ajustado, permite la comparación entre diferentes modelos, aunque el valor mínimo que tiene que alcanzar el coeficiente para comenzar a considerar que es representativo varía en función del que realiza el estudio. 

Este valor se calcula mediante la ecuación (), en donde SSr es la medida de la variabilidad del modelo de regresión y la SSt es la correspondiente a la medida de la variabilidad del valor sin considerar el efecto de la variable explicativa t

$$
R^2 = \frac{SS_R}{SS_t} , 0 ≤ R^2 ≤ 1
$$

<!--poner formula del Rcuadrado -->










<!-- a parti de aqui se explicaria un poquito mas, se empezaria a hablar de la modelizacion y sus resultados -->